//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserConfiguration
    {
        public int id { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> idTypePermission { get; set; }
        public Nullable<int> idCellarArea { get; set; }
        public Nullable<int> idAssignmentType { get; set; }
        public Nullable<int> idAnchorAssignmentType { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> upDateDate { get; set; }
        public Nullable<System.DateTime> deleteDate { get; set; }
        public string state { get; set; }
    }
}
